version: '3.1'

services:
  postgres14:
    container_name: postgres14
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db/migration:/docker-entrypoint-initdb.d



